.TH MIDIMONSTER 1 "December 2019"
.SH NAME
midimonster \- Multi-protocol translation tool
.SH SYNOPSIS
.B midimonster
.I config-file
.SH DESCRIPTION
.B MIDIMonster
allows the user to translate any channel on one supported protocol into channel(s)
on any other (or the same) supported protocol.
.SH OPTIONS
.TP 
.I config-file 
The configuration file to read. If not specified, a default configuration file is read.
.SH "SEE ALSO"
Online documentation and repository at https://github.com/cbdevnet/midimonster
.SH AUTHOR
Fabian "cbdev" Stumpf <fjs at fabianstumpf dot de>
